;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Dao.Mu.YiYe",DevComment="木道一叶草蛊")
+GameplayTagList=(Tag="Dao.Yan.DanHuoGu",DevComment="炎道丹火蛊")
+GameplayTagList=(Tag="GameplayCue.Dash.Active",DevComment="")

